spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bLOG
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
