spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_network
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    enabled: false  # Disable security for testing
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

server:
  port: 8088
