spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/News-page-users
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    url: jdbc:postgresql://localhost:5432/News-page-users
    user: username
    password: password
    enabled: true

server:
  port: 8082