spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9098/realms/News-Page"
  config:
    import: optional:configserver:http://localhost:8080
  application:
    name: gateway


